# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
AWSTemplateFormatVersion: "2010-09-09"
Description: GitHub Actions AWS SAM POC - Setup

Resources:
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: !Sub "cloudformation.${AWS::URLSuffix}"
          Action: "sts:AssumeRole"
          Condition:
            StringEquals:
              "aws:SourceAccount": !Ref "AWS::AccountId"
      Description: !Sub "DO NOT DELETE - Used by CloudFormation. Created by CloudFormation ${AWS::StackId}"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      PermissionsBoundary: !Ref DeveloperBoundary

  DeveloperBoundary:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Permission boundary for developers
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowModifyIamRolesWithBoundary
            Effect: Allow
            Action:
              - "iam:AttachRolePolicy"
              - "iam:CreateRole"
              - "iam:DeleteRolePolicy"
              - "iam:DetachRolePolicy"
              - "iam:PutRolePermissionsBoundary"
              - "iam:PutRolePolicy"
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/app/*"
            Condition:
              ArnEquals:
                "iam:PermissionsBoundary": !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/PermissionsBoundary"
          - Sid: AllowModifyIamRoles
            Effect: Allow
            Action:
              - "iam:DeleteRole"
              - "iam:TagRole"
              - "iam:UntagRole"
              - "iam:UpdateAssumeRolePolicy"
              - "iam:UpdateRole"
              - "iam:UpdateRoleDescription"
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/app/*"
          - Sid: OverlyPermissiveAllowedServices
            Effect: Allow
            Action:
              - "lambda:*"
              - "logs:*"
            Resource: "*"

  GitHubRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Federated: !Ref GitHubProvider
          Action: "sts:AssumeRoleWithWebIdentity"
          Condition:
            StringEquals:
              "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
            StringLike:
              "token.actions.githubusercontent.com:sub": "repo:jplock/gha-aws-sam-poc:*"
      Description: !Sub "DO NOT DELETE - Used by GitHub Actions. Created by CloudFormation ${AWS::StackId}"
      Policies:
        - PolicyName: GitHubPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "iam:PassRole"
                Resource: !GetAtt CloudFormationRole.Arn
                Condition:
                  StringEquals:
                    "aws:ResourceAccount": "${aws:PrincipalAccount}"
                    "iam:PassedToService": !Sub "cloudformation.${AWS::URLSuffix}"
              - Effect: Allow
                Action:
                  - "cloudformation:ContinueUpdateRollback"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:RollbackStack"
                  - "cloudformation:UpdateStack"
                Resource: !Sub "arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stack/app-*"
                Condition:
                  ArnLike:
                    "cloudformation:RoleArn": !GetAtt CloudFormationRole.Arn
                  "Null":
                    "cloudformation:ImportResourceTypes": true
              - Effect: Allow
                Action:
                  - "cloudformation:CancelUpdateStack"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DetectStackDrift"
                  - "cloudformation:DetectStackResourceDrift"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:TagResource"
                  - "cloudformation:UntagResource"
                  - "cloudformation:UpdateTerminationProtection"
                Resource: !Sub "arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stack/app-*"
              - Effect: Allow
                Action:
                  - "cloudformation:CreateUploadBucket"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ValidateTemplate"
                  - "cloudformation:EstimateTemplateCost"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                Resource: !Sub "${ArtifactBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketLocation"
                Resource: !GetAtt ArtifactBucket.Arn

  GitHubProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      ClientIdList:
        - "sts.amazonaws.com"
      Tags:
        - Key: "aws-cloudformation:stack-name"
          Value: !Ref "AWS::StackName"
        - Key: "aws-cloudformation:stack-id"
          Value: !Ref "AWS::StackId"
        - Key: "aws-cloudformation:logical-id"
          Value: GitHubProvider
      ThumbprintList:
        # @see https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
        - "1c58a3a8518e8759bf075b76b750d4f2df264fcd"
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
      Url: https://token.actions.githubusercontent.com

  ArtifactBucket:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: RetentionRule
            Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  ArtifactBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${ArtifactBucket.Arn}/*"
              - !GetAtt ArtifactBucket.Arn
            Condition:
              Bool:
                "aws:SecureTransport": false

Outputs:
  CloudFormationRoleArn:
    Description: CloudFormation IAM Role ARN
    Value: !GetAtt CloudFormationRole.Arn
  GitHubRoleArn:
    Description: GitHub Actions IAM Role ARN
    Value: !GetAtt GitHubRole.Arn
  ArtifactBucket:
    Description: Artifact Bucket Name
    Value: !Ref ArtifactBucket
