# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
AWSTemplateFormatVersion: "2010-09-09"
Description: GitHub Actions AWS SAM POC Setup

Resources:
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: !Sub "cloudformation.${AWS::URLSuffix}"
          Action: "sts:AssumeRole"
          Condition:
            StringEquals:
              "aws:SourceAccount": !Ref "AWS::AccountId"
      Description: !Sub "DO NOT DELETE - Used by CloudFormation. Created by CloudFormation ${AWS::StackId}"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      PermissionsBoundary: !Ref DeveloperBoundary

  DeveloperBoundary:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Permission boundary for developers
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowModifyIamRolesWithBoundary
            Effect: Allow
            Action:
              - "iam:AttachRolePolicy"
              - "iam:CreateRole"
              - "iam:DeleteRolePolicy"
              - "iam:DetachRolePolicy"
              - "iam:PutRolePermissionsBoundary"
              - "iam:PutRolePolicy"
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/app/*"
            Condition:
              ArnEquals:
                "iam:PermissionsBoundary": !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/PermissionsBoundary"
          - Sid: AllowModifyIamRoles
            Effect: Allow
            Action:
              - "iam:DeleteRole"
              - "iam:TagRole"
              - "iam:UntagRole"
              - "iam:UpdateAssumeRolePolicy"
              - "iam:UpdateRole"
              - "iam:UpdateRoleDescription"
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/app/*"
          - Sid: OverlyPermissiveAllowedServices
            Effect: Allow
            Action:
              - "lambda:*"
              - "logs:*"
            Resource: "*"

  GitHubRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Federated: !Ref GitHubProvider
          Action: "sts:AssumeRoleWithWebIdentity"
          Condition:
            StringEquals:
              "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
            StringLike:
              "token.actions.githubusercontent.com:sub": "repo:jplock/gha-aws-sam-poc:*"
      Description: !Sub "DO NOT DELETE - Used by GitHub Actions. Created by CloudFormation ${AWS::StackId}"
      Policies:
        - PolicyName: GitHubPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "iam:PassRole"
                Resource: !GetAtt CloudFormationRole.Arn
                Condition:
                  StringEquals:
                    "aws:ResourceAccount": "${!aws:PrincipalAccount}"
                    "iam:PassedToService": !Sub "cloudformation.${AWS::URLSuffix}"
              - Effect: Allow
                Action:
                  - "cloudformation:ContinueUpdateRollback"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:RollbackStack"
                  - "cloudformation:UpdateStack"
                Resource: !Sub "arn:${AWS::Partition}:cloudformation:*:*:stack/app/*"
                Condition:
                  ArnLike:
                    "cloudformation:RoleArn": !GetAtt CloudFormationRole.Arn
                  "Null":
                    "cloudformation:ImportResourceTypes": true
              - Effect: Allow
                Action:
                  - "cloudformation:CancelUpdateStack"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DetectStackDrift"
                  - "cloudformation:DetectStackResourceDrift"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:TagResource"
                  - "cloudformation:UntagResource"
                  - "cloudformation:UpdateTerminationProtection"
                Resource: !Sub "arn:${AWS::Partition}:cloudformation:*:*:stack/app/*"
              - Effect: Allow
                Action:
                  - "cloudformation:CreateUploadBucket"
                  - "cloudformation:ValidateTemplate"
                  - "cloudformation:EstimateTemplateCost"
                Resource: "*"

  GitHubProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      ClientIdList:
        - "sts.amazonaws.com"
      Tags:
        - Key: "aws-cloudformation:stack-name"
          Value: !Ref "AWS::StackName"
        - Key: "aws-cloudformation:stack-id"
          Value: !Ref "AWS::StackId"
        - Key: "aws-cloudformation:logical-id"
          Value: GitHubProvider
      ThumbprintList:
        # @see https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
        - "1c58a3a8518e8759bf075b76b750d4f2df264fcd"
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
      Url: https://token.actions.githubusercontent.com

Outputs:
  GitHubRoleArn:
    Description: GitHub Actions IAM Role ARN
    Value: !GetAtt GitHubRole.Arn
